DOMAIN = "meteoalarm_map"
CAMERA_NAME = "Meteoalarm Europe"
SENSOR_NAME = "Meteoalarm Alerts"
IMAGE_PATH = "/config/www/meteoalarm_map.png"
URL = "https://www.meteoalarm.org/en/live/"
RSS_FEED = "https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-rss-europe"